### ISSUE TITLE
Update Gluon to Version 2016.x

### ISSUE THREAD

**Issue by mortzel** [freifunk-fulda/orga#105] opened 2016-01-08 18:53 UTC
To support the new TP-Link WR841N/D v10 we should upgrade our gluon version to v2016.1

**Comment by reissmann** [comment] 2016-07-12 21:08
done.

**Comment by fooker** [comment] 2016-07-14 08:45
How is this done? Support for this particular device was backported to gluon 2015.1.x and it's therefore available in our firmware. But due to problems with Archer C7, we're stil sticked to 2015.1.x releases.

There is a test build for gluon 2016.1 in the branch issues/105 but development got stuck caused by the problems described above.

I'v changed the toppic accordingly and reopen this bug.

**Comment by Jo-Jo0** [comment] 2016-11-24 21:54
The archer c7 Problems should be fixed in gluon 2016.2.x. In issues/105 is a Firmware that should work. We should consider #144 and then think of rooling this out.

**Comment by Jo-Jo0** [comment] 2016-12-07 22:44
done (see development branch)

**Closed as completed** 2016-12-07 22:45 UTC
Labels: enhancement, firmware
